### PR TITLE
Creating a single Dockerfile

### PR DESCRIPTION
**Pull request by MrNuggelz**
I have created a single Dockerfile to simplify the installation. I also added a Dockerfile which ships with mariadb reducing the installation to only one call.

### CODE REVIEW

**Comment by RyanNoelk** [comment]
Thanks for the PR. This is something I've been thinking about doing for some time. I'll take a look at this over the next few days and let you know if I have any questions.

**Comment by MrNuggelz** [comment]
I now also added a button to try the project on labs.play-with-docker.com

**Comment by hoijui** [comment]
I see this has alreayd been merged, right?

**Comment by mcrodrig** [comment]
Any progress on this? I would like to have an unique container if possible.

**Comment by MrNuggelz** [comment]
The image itself is finished, but still needs to be merged.
Until then you can use the image I uploaded to dockerhub: https://hub.docker.com/r/maduvef/openeats
Or you can build it yourself using my fork: https://github.com/MrNuggelz/OpenEats/tree/master/alpine

**Comment by mcrodrig** [comment]
Yes, but it is 10 months old. Any reason for not having merged it? The PR is there for almost a year. Is OpenEats still being developed?

**Comment by RyanNoelk** [comment]
I haven't merged it yet cause I don't have much time to devote to updating this. I leave this open so that I people what to use the fork that @MrNuggelz created, they can use that.

**Comment by budda85** [comment]
Maybe someone can help me.

> The image itself is finished, but still needs to be merged.
> Until then you can use the image I uploaded to dockerhub: https://hub.docker.com/r/maduvef/openeats
> Or you can build it yourself using my fork: https://github.com/MrNuggelz/OpenEats/tree/master/alpine

I've created the container from dockerhub on my synology NAS. I am using die MariaDB from the NAS. everthing is working but when i visit the website. Django shows me this warning:
`Invalid HTTP_HOST header: '192.168.0.90:7400'. You may need to add '192.168.0.90' to ALLOWED_HOSTS.`
Add ALLOWED_HOSTS to my variables has no effect.

**Comment by hertfelder** [comment]
I really like the separation into three containers. It is clean and "the docker way". I can understand that some people want to have one image only. However, the majority will appreciate the separation, I think.

**Comment by LukasdeBoer** [comment]
Running this in a single container would make it a lot easier for people to run this on their devices. Not everyone wants to docker-compose on their Synologies :-)

**Comment by hertfelder** [comment]
You could also use a simple shell script with the respective docker run commands, if you don't want to/can't use docker-compose. But I understand, that one image would be easier to use in this case. Had it running on a raspberry pi before migrating to the production environment and even that worked (after compiling images for armv7 though) :)

**Comment by CorneliousJD** [comment]
> `Invalid HTTP_HOST header: '192.168.0.90:7400'. You may need to add '192.168.0.90' to ALLOWED_HOSTS.`
> Add ALLOWED_HOSTS to my variables has no effect.

You need ALLOWED_HOST (no S at the end) -- I ran into this too. Looks like Django calls it HOSTS w/ the S but the OpenEats team uses it w/out the S for the variable.

**Comment by CorneliousJD** [comment]
> The image itself is finished, but still needs to be merged.
> Until then you can use the image I uploaded to dockerhub: https://hub.docker.com/r/maduvef/openeats
> Or you can build it yourself using my fork: https://github.com/MrNuggelz/OpenEats/tree/master/alpine

Hey there @MrNuggelz , in the file https://github.com/MrNuggelz/OpenEats/blob/master/alpine/mariadb/Dockerfile

There's somethign wrong, the startup still isn't executable in this one for some reason. 
When trying to run this I get `error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: "/startup/start.sh": permission denied": unknown.`

I was building an unRAID docker template, got the one withOUT MariaDB baked in up and running, but the one with refuses to run because of this, if you're able to fix that I can update my template and it would open this up for even more users! :) 

Thanks in advance.

PS - I tried to submit an issue on that repo but it doesn't look like issue tracking is enabled there.

**Comment by schizzle** [comment]
> 

> 
> 
> > The image itself is finished, but still needs to be merged.
> > Until then you can use the image I uploaded to dockerhub: https://hub.docker.com/r/maduvef/openeats
> > Or you can build it yourself using my fork: https://github.com/MrNuggelz/OpenEats/tree/master/alpine
> 
> Hey there @MrNuggelz , in the file https://github.com/MrNuggelz/OpenEats/blob/master/alpine/mariadb/Dockerfile
> 
> There's somethign wrong, the startup still isn't executable in this one for some reason.
> When trying to run this I get `error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: "/startup/start.sh": permission denied": unknown.`
> 
> I was building an unRAID docker template, got the one withOUT MariaDB baked in up and running, but the one with refuses to run because of this, if you're able to fix that I can update my template and it would open this up for even more users! :)
> 
> Thanks in advance.
> 
> PS - I tried to submit an issue on that repo but it doesn't look like issue tracking is enabled there.

You need to change the command to `["sh", "-c", "chmod -R +x /startup ; /startup/start.sh"]`. The docker image is also slightly behind the repo.

**Comment by CorneliousJD** [comment]
> You need to change the command to `["sh", "-c", "chmod -R +x /startup ; /startup/start.sh"]`. The docker image is also slightly behind the repo.

I was actually pulling from his dockerhub to build it in unraid, so I was hoping he would be able to make that modification to trigger a new build on dockerhub for the mariadb tagged release so I could get it out to the masse on unRAID. 

Also that dockerfile lets you set a variable for OPENEATS_VERSION to 1.5.1 or even "master" to pull direct from the repo it seems.

**Comment by CorneliousJD** [comment]
I am still getting the following error for what it's worth.
Also, if we do ge this fixed, where is the mariadb database stored at? I would need to map it to persistent storage in unRAID so container restarts/upgrades dont kill it. 
`/usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: "/startup/start.sh": permission denied": unknown.`

**Comment by MrNuggelz** [comment]
I have updated the mariadb image, correcting the permissions and building from master.

**Comment by CorneliousJD** [comment]
> I have updated the mariadb image, correcting the permissions and building from master.

I have the regular one working fine when supplying my own database, but the mariadb one is still failing, although getting furhter than before now.

It actually launches the container, and I get

```
[i] MySQL data directory not found, creating initial DBs
[i] Creating database: openeats
[i] Creating user: openeats with password openeats
--more Note/InnoDB lines here--
ERROR: 1049 Unknown database 'mysql'
2020-05-27 9:36:26 0 [ERROR] Aborting
--more Note/InnoDB lines here--
2020-05-27 9:36:29 0 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2020-05-27 9:36:30 0 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
2020-05-27 9:36:30 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)")
```

I'm not sure what's causing this stuff though, again I have it working with providing my own database, but was hoping if I could get this one with MariaDB built in I could open this up for even more people to use that didn't want to bother with a separate DB container.

Anything I can do to help/test just let me know.

**Review by CorneliousJD — APPROVED** [review]

**Review by bruceschaller — APPROVED** [review]
Everything as expected here.

**Comment by bruceschaller** [comment]
Any chance we can move these changes to a LATEST branch and set the current master to a version 1?  Onwards and upwards!  Good riddance 2020... happy new year!

**Comment by rustymyers** [comment]
If anyone is interested in these pulls being merged, please let me know. I'm unsure what this will break, but willing to move forward with a single docker file...unless something else is better?

**Review by rustymyers — APPROVED** [review]
Changes look appropriate for single docker container

**Pull request merged**
